package-lock.json
package.json
script/bump-version

Until now we haven't actually set the version number in the package.json.
Since we plan to start a v2 development line as part of upgrading to Node 16 in #78, this establishes the work to date as v1.0.0.

v1.0.0 release notes

---

.github/workflows/dependabot-build.yml

When a Dependabot PR is opened, if the updated dependency is classified as a `production` update let's go ahead and run `npm run package` and check in the results so a human maintainer doesn't need to pull the branch and do it.
This is limited to `production` packages as it's pretty unexpected that any development dependency would modify the build, so it would be better to flag that by leaving the branch in a failing state.

Automatically update dist/ files for Dependabot bumps

---

package-lock.json
package.json

* Bump ts-jest from 27.0.7 to 27.1.3 by @dependabot in https://github.com/dependabot/updater-action/pull/65
* Bump @types/node-forge from 0.10.3 to 1.0.0 by @dependabot in https://github.com/dependabot/updater-action/pull/60
* Automatically update dist/ files for Dependabot bumps by @brrygrdn in https://github.com/dependabot/updater-action/pull/83
* Bump @actions/core from 1.5.0 to 1.6.0 by @dependabot in https://github.com/dependabot/updater-action/pull/20
* Bump @octokit/webhooks-types from 4.8.0 to 5.4.0 by @dependabot in https://github.com/dependabot/updater-action/pull/85
* Bump jest from 27.3.1 to 27.5.1 by @dependabot in https://github.com/dependabot/updater-action/pull/86
* Use automatically updated Dockerfiles to set the tag of the updater/proxy used. by @brrygrdn in …

v2.0.1 Release Notes

---

__tests__/docker-tags.test.ts
dist/main/index.js
docker/Dockerfile.proxy
docker/Dockerfile.updater
docker/containers.json

Extracts the final touch from #72 to move us off the `v1` reference for both containers to using actual SHAs.
The versions I've checked in as part of this commit are deliberately 1 version behind `latest` of both. This is so that two things happen:
- We verify Dependabot generates PRs to update us to the correct version(s)
- We have Dependabot PRs we can use to validate our build Action workflow to compile the `dist/` folder using the SHA automagically ✨ 
This should not merge until https://github.com/dependabot/updater-action/pull/91 has been released as I would like to release the refactor to _enable_ this change ahead of the actual container swap over so its easier to test each in isolation.
This gives us affordance to have the `v2` tag fall back from to `v2.0.1` in the event we …

Switch to using explicit container SHAs

---

.github/workflows/dependabot-build.yml

When Dependabot bumps the version of our Docker containers, we need to add an extra step to our build workflow that refreshes the `docker/containers.json` manifest file that we compile.
This updates the workflow to:
- Become aware of the `package-ecosystem` a Dependabot PR addresses
- Perform the build if the ecosystem is docker -or- the ecosystem is npm *and* it relates to a production dependency
- Insert an extra step before we regenerated the `dist/` folder to prepare and check in the manifest changes

Build the containers manifest for Dependabot Docker PRs

---

__tests__/docker-tags.test.ts
dist/main/index.js
docker/Dockerfile.proxy
docker/Dockerfile.updater
docker/containers.json
src/update-containers.ts

Update the action to use the latest release SHAs for both containers:
https://github.com/dependabot/dependabot-updater/pkgs/container/dependabot-updater%2Fdependabot-updater
https://github.com/github/dependabot-update-job-proxy/pkgs/container/dependabot-update-job-proxy%2Fdependabot-update-job-proxy
This update is being performed manually as I'm currently investigating some issues with the automation around this but I do not want to block testing and preparing v2.1.0 any further.

Update containers to the latest release SHAs

---

package-lock.json

`strip-ansi` specifically seems to be referencing a version of `ansi-regex` with an advisory against it, so let's patch it.

Bump ansi-regex downstream deps

---

dist/cleanup/index.js
dist/main/index.js
docker/Dockerfile.proxy
docker/Dockerfile.updater
docker/containers.json

https://github.com/github/dependabot-update-job-proxy/pkgs/container/dependabot-update-job-proxy%2Fdependabot-update-job-proxy/16074873?tag=latest
https://github.com/dependabot/dependabot-updater/pkgs/container/dependabot-updater%2Fdependabot-updater/16182948?tag=latest
Our automation is still having some issues with credentials, let's just update these containers manually so we can finalise the 2.1.0 release.

Manually update our containers to the latest versions

---

package-lock.json
package.json
script/bump-version

* Switch to using explicit container SHAs by @brrygrdn in https://github.com/dependabot/updater-action/pull/92
* Build the containers manifest for Dependabot Docker PRs by @brrygrdn in https://github.com/dependabot/updater-action/pull/93
* Update containers to the latest release SHAs by @brrygrdn in https://github.com/dependabot/updater-action/pull/95
* Ensure we wait for container downloads if they don't exist by @brrygrdn in https://github.com/dependabot/updater-action/pull/96
* Fix cleanup of network and containers by @brrygrdn in https://github.com/dependabot/updater-action/pull/97
* Cleanup old image versions by @brrygrdn in https://github.com/dependabot/updater-action/pull/98
* Bump follow-redirects from 1.14.7 to 1.14.9 by @dependabot in …

V2.1.0 release notes

---

.github/dependabot.yml

We are now using `ghcr.io` for our images which permits anonymous access.
Our latest update run verifies this is working as intended without these credentials.

[Dependabot Updates] Remove the docker registry

---

package-lock.json
package.json
script/bump-version

* Improve annotation of failed jobs by @brrygrdn in https://github.com/github/dependabot-action/pull/113
* Bump dependabot/fetch-metadata from 1.2.1 to 1.3.0 by @dependabot in https://github.com/github/dependabot-action/pull/108
* Bump actions/setup-node from 2.5.1 to 3 by @dependabot in https://github.com/github/dependabot-action/pull/99
* Bump actions/checkout from 2 to 3 by @dependabot in https://github.com/github/dependabot-action/pull/107
* Bump ts-node from 10.2.1 to 10.7.0 by @dependabot in https://github.com/github/dependabot-action/pull/111
* Enable connectivity check by @mctofu in https://github.com/github/dependabot-action/pull/120
* Update CODEOWNERS for org shift by @mctofu in https://github.com/github/dependabot-action/pull/121
* Switch from GHPR to GHCR for images by …

V2.2.0 release notes

---

dist/cleanup/index.js
dist/main/index.js
docker/Dockerfile.updater
docker/containers.json

Our automation isn't working as intended currently, so this is a manual bump.
Notable change: `dependabot-updater` is now able to respect an ENV var that was introduced in #130.

Bump `dependabot-updater` to pull in updates

---

.github/dependabot.yml
.github/workflows/check-dist.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml
.github/workflows/integration-test.yml
.github/workflows/test.yml

We want to start using Dependabot updates to establish a maximum release frequency of 1 minor patch per month to keep our dependencies up to date.
In order to make this process as painless as possible, this PR collects a few improvements:
- Fix a malformed condition that was causing the automatic build to **always** skip
- Add a workflow to enable the automerge feature for any Dependabot PRs
- PRs still require an approval from a required reviewer to actually merge, this just reduces friction

Dependabot updates run monthly and enable automerge

---

dist/cleanup/index.js
dist/main/index.js
docker/Dockerfile.proxy
docker/Dockerfile.updater
docker/containers.json

In preparation for GHES 3.6, I'm updating the `dependabot-update-job-proxy` and `dependabot-updater` images. Once approved/merged, a new tag and release will be created (`ghes-3.6`), and the `v2` tag will be updated to use these images.

Update Docker images for `ghes-3.6` release

---

dist/cleanup/index.js
dist/main/index.js
docker/Dockerfile.updater
docker/containers.json

There are a couple reasons our automation has been broken around keeping our images up-to-date:
* A typo in the corresponding workflow prevented the update image step
from running
* The images were using non-incrementable versions
* Dependabot could not reliably assume that one version is greater
than another
The workflow has been fixed. This PR sets the updater image to a version that Dependabot will be able to update (`v2.0.20220623221933`)

Set updater image to an incrementable version

---

.github/workflows/dependabot-build.yml

We've had several builds fail because the `dist/` directory has changes in it after it builds. I don't know the history of excluding dev dependencies from this check, but it seems to be wrong.

Build the `dist/` directory for dev depenencies

---

.github/workflows/check-dist.yml
.github/workflows/dependabot-build.yml
.github/workflows/integration-test.yml
.github/workflows/test.yml

Hi GitHub!
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
As per this URL, set-output of Github Actions is deprecated.
I would like to create a PR for a fix.
Thanks.

fix(ci): replace set-output to GITHUB_OUTPUT

---

action.yml

.nvmrc is already set to 16 so this might have just been missed.

Node 12 actions are deprecated, bump to 16

---

.github/workflows/integration-test.yml
dist/cleanup/index.js
dist/main/index.js
docker/Dockerfile.updater
docker/containers.json

This updates the updater to one of the most recent releases, v2.0.20221205081158.
https://github.com/dependabot/dependabot-core/pkgs/container/dependabot-updater/56976628?tag=v2.0.20221205081158

Bump updater to v2.0.20221205081158

---

.github/dependabot.yml

We only need to update when prepping a new release so daily is too frequent. Changing to monthly to be more in line with the other configs but we'll likely manually trigger the update for a release anyway.

Change docker updates to monthly schedule

---

.github/workflows/dependabot-build.yml

This is an aesthetic tweak to let the proper avatar show up:
* https://github.com/orgs/community/discussions/26560
* https://github.com/actions/checkout/pull/1184
Similar to:
* https://github.com/dependabot/fetch-metadata/pull/354

Use the full email for the GitHub Actions bot

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml

This is mostly cosmetic, since we control the action so aren't worried about something nefarious happening. But it's also good practice, and makes our security bot reviewer happy.

Pin `fetch-metadata` by SHA

---

.github/dependabot.yml

There are multiple deps that are `eslint`-related, and since they're all related to a linter, it's very safe to merge them as a single group.

Group :dependabot: PR's for `eslint`-related deps

---

.github/dependabot.yml

I've included all of the `devDependencies` from `package.json` here. Are there any that would be better to handle as individual PRs?

Add a group for all dev dependencies

---

.github/dependabot.yml

So they'll be ready to review before monday starts.

Shift dependabot version updates to Sunday

---

.github/dependabot.yml

Major updates are more likely to break CI, so let's open separate PRs for those. Also use the new-fangled `dependency-type` config options instead of listing all the deps out.

Only group patch and minor dev-dependencies

---

.github/workflows/check-dist.yml
.github/workflows/dependabot-build.yml
.github/workflows/integration-test.yml
.github/workflows/test.yml

We don't need to manually read it because `actions/setup-node` supports directly reading the `.nvmrc` file.
We already did this change over a year ago in `fetch-metadata` here:
* https://github.com/dependabot/fetch-metadata/pull/370

Start using `node-version-file` param

---

.npmrc

While reviewing some logs, I noticed the following:
```shell
added 1 package, changed 30 packages, and audited 382 packages in 6s
58 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
While I'm not against security, nor supporting OSS maintainers (I co-maintain 10+ projects myself!), I am against noisy logs that add no value.
So let's silence these:
1. When they appear in CI, they add no value.
1. We've got our own security tools for vulnerable deps, which we rely on instead of `npm audit` results.
1. When I'm skimming logs looking for debug information, these just get in my way.
1. There may be a speed boost if the audit/fix metadata requires an additional API call,  and silencing actually skips that rather than merely silencing it.
There's multiple …

Silence audit and funding messages from `npm`

---

__tests__/updater-builder-integration.test.ts

The test default timeout is 5 seconds. The `beforeAll` step has a separate timeout.
This test was timing out originally at 9 seconds, so that indicates the `beforeAll` step takes around 4 seconds.
Experimenting showed the test completes around 12-15 seconds, of which 4 seconds are the `beforeAll` step, so the test itself takes 8-11 seconds. But I forgot we have auto-merge enabled, so my experimental timeout of 30 seconds got merged when I wasn't planning to...
A 15 second timeout should be all we need.

Set the test timeout to 15 seconds

---

README.md

Several customers have requested instructions for manually upgrading Dependabot on their GHES instance.
So this provides some helpful breadcrumbs.

Add instructions for manually upgrading on GHES

---

.husky/pre-commit

Saw this warning in the logs:
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
→ No staged files match any configured task.
```

Remove deprecated command invocation

---

.github/workflows/dependabot-auto-merge.yml

The `fetch-metadata` step isn't used, so removed it.
I checked `git blame` and this appears to have been unused from the start, not sure how it crept in here.
This is in-preparation to a follow-on PR that will swap away from using a PAT... I split it out as there's a few ways we may eliminate the PAT, so wanted to be sure to land this regardless.

Remove unused `fetch-metadata` step

---

.github/workflows/check-dist.yml
.github/workflows/codeql-analysis.yml
.github/workflows/integration-test.yml
.github/workflows/test.yml

Applying https://github.com/dependabot/fetch-metadata/pull/617 over here:
> I'm copying the setup of one of these actions to another repo, and the hardcoding of `ref` surprised me... these should be the same as the default behavior. I checked with Barry who originally committed these files, and he didn't remember why... possibly he'd hardcoded them when testing the action and forgot to remove them.
> 
> So let's pull them out to remove confusion.

Remove unnecessary hardcoding of `ref`

---

.github/workflows/check-dist.yml
.github/workflows/dependabot-build.yml
.github/workflows/integration-test.yml
.github/workflows/test.yml

The `setup-node` action now supports caching the results of `npm install`/`npm ci`: 
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

Enable caching of `npm install`/`npm ci` for `setup-node` action

---

.github/dependabot.yml

Previously we were using a user-based PAT, but those expire every 90 days.
By switching to the federated token, it gets rotated/audited by the security team, and not something we have to maintain.
This is a public repo, so I can't link here to internal stuff, but this is blocked on an internal PR to setup the federation link.

Switch from PAT to federated secret for pulling ghcr images

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml

Switch to using an App token instead of a PAT

Switch to using an App token instead of a PAT

---

__tests__/main.test.ts
__tests__/updater-builder-integration.test.ts
__tests__/updater.test.ts
src/api-client.ts
src/updater.ts

We're adding new ways to provide credentials to the Dependabot job. The job definition contains metadata for the credentials, in order to do things like generate an npmrc on-the-fly.
To simplify things, we're moving the metadata generation to the Action. It's the perfect place to do it, right before starting the job we have all the information we need to generate it.
For safety we use an "allow list" strategy, that way newly added credentials will not suddenly appear in the job definition.

generate credentials metadata

---

__tests__/updater.test.ts
src/updater.ts

- More of https://github.com/github/dependabot-action/pull/1519
Added two more registry types that could use the URL -> registry behavior.

extract registry from url for other ecosystems

---

__tests__/updater.test.ts
src/updater.ts

- Same as #1519
Setting index-url if it's not there when url is present.

set index-url from url
